Add feature model metamodel extension
BESSER-PEARL/BESSER pull request #132
Opened 2024-12-10 10:16 UTC by mgv99

2025-01-12 15:31 UTC, ivan-alfonso requested changes

2025-01-12 15:31 UTC, ivan-alfonso commented on besser/BUML/metamodel/feature_model/__init__.py
Please add this line

``` from .feature_model import * ```

2025-01-12 15:31 UTC, ivan-alfonso commented on besser/BUML/metamodel/feature_model/feature_model.py
Some comments:

### 1. Default Mutable Arguments in Constructors 
There are empty lists assigned by default in some variables in the constructor methods. This can cause issues because lists are mutable objects shared between instances.

For example, in line 113:

```features: list[Feature] = []```

If you define the following:

f1 = FeatureGroup(kind="MANDATORY")
f1.features.append(1)
f2 = FeatureGroup(kind="MANDATORY")

Then ```f1.features``` will be the same as ```f2.features```, which creates unintended shared states.

A simple fix for this issue is to use None as the default value and initialize the list inside the constructor:

```python
def __init__(self, kind: str, features: List[Feature] = None):
    if features is None:
        features = []
    self.features: List[Feature] = features
```

### 2. Type Annotation

I think the standard way to define the code in line 139 is:

```python
from typing import Union
self.value: Union[int, float, str] = None
```

### 3 value Attribute in FeatureConfiguration Constructor

The ```value``` attribute of the ```FeatureConfiguration``` class is not included in the ```__init__``` method parameters. This means the value cannot be specified during the creation of an object. Is this omission intentional?

### 4 Missing relationship

It seems that the ```has_children``` relationship between ```FeatureGroup``` and ```Feature``` is  either not directly implemented or not clearly defined.

2025-01-12 15:31 UTC, ivan-alfonso commented on docs/source/img/feature_model_mm.png
To maintain consistency with the rest of the BESSER metamodels, here are some suggestions for the metamodel figure:

* The names of the associations or end names should not contain spaces. For example, update the names to use underscores (_) instead: Replace ```has features``` with ```has_features``` or simply ```features```

* The small arrow in the association names is unnecessary. Instead, position the label closer to the appropriate end of the association to indicate the direction. For example, move the ```has_features``` label closer to the ```Feature``` end to indicate that the list of Features can be accessed from ```FeatureGroup``` using this label.

2025-01-29 16:37 UTC, mgv99 commented on docs/source/img/feature_model_mm.png
Changes applied in 4999f1f87c348365a65e3ea044f1f7130e753326, see new figure

2025-01-29 16:39 UTC, mgv99 commented on besser/BUML/metamodel/feature_model/feature_model.py
Sections 1, 2 and 3: changes applied in 4999f1f87c348365a65e3ea044f1f7130e753326
Section 4: relationship exists, see Feature.children_groups (list[FeatureGroup])

2025-01-29 16:48 UTC, mgv99 commented on besser/BUML/metamodel/feature_model/__init__.py
Done in 4999f1f87c348365a65e3ea044f1f7130e753326

2025-02-05 10:53 UTC, merged